# Generated by Django 4.2.1 on 2023-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cgpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/images"),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
