# Generated by Django 4.2.1 on 2023-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_student_cgpa_alter_student_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
